version: 2
updates:
  - package-ecosystem: gradle
    directory: "chat-backend"
    schedule:
      interval: daily
    open-pull-requests-limit: 10
  - package-ecosystem: 'npm'
    directory: 'chat-frontend'
    schedule:
      interval: 'daily'
    open-pull-requests-limit: 10
