pull_request_rules:
  - name: Dependabot automatic merge
    conditions:
      - and :
        - author=dependabot[bot]
        - check-success=lift
        - or :
          - and :
            - check-success=build
            - check-success=codecov/project
          - and :
            - check-success=build (17.x)
            - check-success=build (18.x)
    actions:
      merge:
        method: merge
  - name: delete head branch on merged pull requests
    conditions:
      - merged
    actions:
      delete_head_branch: