spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8081/auth/realms/chat
  data:
    mongodb:
      database: chats
      username: root
      password: password
      authentication-database: admin
      auto-index-creation: true
      uuid-representation: standard
  rsocket:
    server:
      transport: websocket
      port: 9090
#server:
#  port: 8080