name: rsocket-chat-frontend-ci
on:
  push:
    paths:
      - 'chat-frontend/**'
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [17.x, 18.x]
    defaults:
      run:
        working-directory: ./chat-frontend
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    # - run: npm ci
    - run: npm install
    - run: CI=false npm run build
    # - run: npm run test
